name: stoky_mobile
description: STOKY - AI-Powered Stock Advisor Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Essential dependencies only
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
